szimek/signature_pad

src/signature_pad.js

This change prevents iOS Safari from firing an mouse down & mouse up event in addition to the touch start and touch end event if you just tap the screen.
This resolves #120.

Prevent duplicate events on tap in iOS Safari

---

signature_pad.js

I understand that this might be a specific issue happening in my project. We're using a generic system where we bind data to various controls, among them your awesome signature pad. When we load something from our database using `fromDataURL` we get a canvas object, even when the string we've passed into the load function was empty. Later on the check for mandatory fields wrongly reports that the field contains a signature.
You can test this by running this:
```javascript
signaturePad.clear();
signaturePad.fromDataURL("");
signaturePad.isEmpty(); // will be false
```
Most people will most likely not have a problem to avoid calling `fromDataURL` when their string is empty, but I still believe that this change would make signature pad a bit more solid.

don't create canvas from empty string

---

src/signature_pad.js

Hey @szimek this is a simple modification to export to SVG with the correct pen color for each stroke.

Export to SVG with correct pen colors

---

CHANGELOG.md
src/signature_pad.js

Dear @szimek,
I know you're as busy as I am :) I'd still kindly ask you consider this PR as a small change that potentially solves a number of issues and PRs in one strike.
It simply allows a custom ratio, width, and height to be passed in when loading an image onto the canvas.
It should solve these Issues:
* The last comment in #89 suggests a monkey patch that is solved by this PR
* #105 appears to be solvable by overriding width/height via `fromDataURL` as implemented in this PR
* #153 complains about guessing the ratio automagically, should be solved by this PR
* #200 describes just the problem that this PR solves
And you should be able to close these PRs:
* #241 suggests to shrink any larger image to the canvas. While this makes sense at first sight, it's probably magic that may not …

Allow custom ratio/width/height in fromDataURL

---

CHANGELOG.md
src/signature_pad.js

Fix `minDistance` not being correctly initialized when set to zero.

---

src/signature_pad.ts

When fast drawing with thicker line settings like `minWidth: 2, maxWidth: 4, velocityFilterWeight: 0.9` big inkt drop are showing on the canvas. It happens mostly around on the corners and start of new lines.

prevent drawCurve exceeding max width

---

src/signature_pad.ts

Fixes #480 
Fixes this error that I'm getting sometimes:
This can happen if `clear()` is called while a signature is still being drawn, so the signature might need to be "restarted" by calling `_strokeBegin` again.

Fix #480 - Fix race condition / edge case in _strokeUpdate where this._data can sometimes be []

---

src/signature_pad.ts

Fix Error Below: 
14:9 Subsequent property declarations must have the same type.  Property 'msTouchAction' must be of type 'string | null', but here has type 'string'.
12 | declare global {
13 |     interface CSSStyleDeclaration {
> 14 |         msTouchAction: string;
|         ^
15 |     }
16 | }
17 | export interface Options {

Fix(msTouch)

---

src/signature_pad.ts

Allow x and y offset to enable centering an image with different dimensions from the canvas.
This is not quite as good as an automatic version which would scale & fit the image to the canvas, but at least it allows all the necessary manual settings.

Allow offsets when loading image via fromDataURL

---

src/signature_pad.ts

Discussion: https://github.com/szimek/signature_pad/issues/399
Tested and it works for my setup. What do we need to get this through ? @szimek

Added Anonymous to crossOrigin prop

---

README.md

using "" instead '' in split will lead to an error :" cannot convert from string to char"

fixing split error

---

src/signature_pad.ts

There is currently an issue in the export of SVGs that causes data to be truncated off the right-hand and bottom.
The problem lies in the fact that stroke data is being recorded in terms of the overall size of the canvas and then the size of the viewBox is being reduced afterwards. It's not necessary to reduce the viewBox's size because the viewBox's width and height are unitless and only meaningful in relation to the stroke data. Reducing the maxX of the viewBox from 1000 to 500, for example, just invalidates coordinates with x > 500 because they no longer exist in the viewBox.
I think the intent of this originally must have been to preserve the dimensions of the image across devices of differing DPI, and for that we only need to adjust the width and height attributes.

Set SVG viewBox size from canvas width and height without factoring by devicePixelDensity

---

src/signature_pad.ts

On Android devices, curve.length() may return a number less than 1.
In other words, if you write a line very very slowly, 
Math.floor() will set the length of the line to 0.
This leads to a bug where the line is not written at all.
This bug can be solved by not using Math.floor().

fix _drawCurve() when moving very slowly

---

docs/js/signature_pad.umd.js
src/signature_pad.ts

- Remove callback for fromDataUrl and return promise instead.
- Remove `onBegin` option and add `beginStroke` event.
- Remove `onEnd` options and add `endStroke` event.
- add `beforeUpdateStroke` and `afterUpdateStroke` events.
fixes #543 
closes #423

use event emitter

---

docs/js/signature_pad.umd.js
src/signature_pad.ts

The "Scribble" feature of iOS intercepts point events. So that we can lose some of them when tapping rapidly. We should use touch events for iOS platforms according to https://developer.apple.com/forums/thread/664108 and https://stackoverflow.com/questions/64314226/ipados-14-apple-pencil-fast-tapping-not-working-html-javascript-ontouchstart/64316781#64316781.
I've tested this solution on iPad Air 2020 with Apple Pencil. It works right.
closes #518

Use touch events for iOS platforms instead of point events

---

README.md

Hi,
A made a small change to the readme.
I noticed that the readme has examples (to be specific addEventListener) which assume you are using v4 of the signature pad. 
However the script tag was still including v2. 
Cheers

updated script tag example

---

src/signature_pad.ts

always clone the input data in `fromData` so that the input is not mutated
- in the clear case, `fromData` would set `this._data = pointGroups`,
which made the pointer the same as the one for the parameter
- as `this._data` is internally mutated, this would cause the input
parameter to also be mutated as a side-effect
- this input mutation side-effect is likely unintended, so patched it so
that the data is cloned in _all_ cases, not only in the append case
- in the clear case, `this._data` is set to an empty array by
`this.clear()`, so this is equivalent to `[].concat(pointGroups)`,
which will result in them all being cloned
Fixes https://github.com/agilgur5/react-signature-canvas/issues/56
Credits to @Zwyx for discovering this in the above issue
Can see that issue for some manual testing …

fix: don't mutate data in `fromData`, clone instead

---

README.md

Add two examples to the README for usage of options with `fromDataURL` and `toDataURL`.
- Apply some misc formatting to the README as well
- some options were added in [v4.0.0](https://github.com/szimek/signature_pad/blob/master/CHANGELOG.md#400) but were not mentioned in the docs
- I've pointed [multiple](https://github.com/agilgur5/react-signature-canvas/issues/75#issuecomment-1089272704) [users](https://github.com/agilgur5/react-signature-canvas/issues/60#issuecomment-1030713591) to the code for this (instead of the docs) as a result
- `fromDataURL` had partial options available [earlier](https://github.com/szimek/signature_pad/blob/8145dd499974df25592be7dbd4c583079a9a26c7/src/signature_pad.js#L99), but no examples, and then offsets were added in v4
- `toDataURL` had options available …

docs: add options to `fromDataURL` (and `toDataURL`)

---

CHANGELOG.md

add note to v4.0.0 changelog that `dotSize` had a breaking change as well
- this was changed to only accept a `number`, whereas it previously accepted a `number` or a `function`
- this was necessary in order to serialize `dotSize` in `#toData` in #571
- found [this line diff](https://github.com/szimek/signature_pad/pull/571/files#diff-1ca065a23dd22378e1c61a8539d9bd5f27a2fc78fbc0c6766645533fc651061cR23) while exploring an upgrade in https://github.com/agilgur5/react-signature-canvas/pull/68#issuecomment-1054862577
There might be more breaking changes missing from the Changelog? c.f. https://github.com/agilgur5/react-signature-canvas/pull/68#issuecomment-1051305044

changelog: add breaking change to v4's `dotSize`

---

src/signature_pad.ts
tests/signature_pad.test.ts

Chrome has started warning when canceling an event that cannot be cancelled, like scrolling.
This causes a fair bit of log spam. I know it fires for touchmove and touchend and there's 
reports that it also fires for touchstart.
IgnoredEventCancel: intervention: Ignored attempt to cancel a touchmove event with
cancelable=false, for example because scrolling is in progress and cannot be interrupted
References:
- https://github.com/react-grid-layout/react-draggable/issues/553
- https://www.uriports.com/blog/easy-fix-for-intervention-ignored-attempt-to-cancel-a-touchmove-event-with-cancelable-false/
- https://github.com/FL3NKEY/scroll-lock/issues/19
- https://stackoverflow.com/a/53315365/30900

fix: check for event.cancelable in touch events

---

src/signature_pad.ts
tests/signature_pad.test.ts

Closes #636
Note that I've only swapped the event target, as the other `document` methods used are not window/document specific. I also didn't touch the `SignatureEventTarget` iOS compatibility part, as it only affects events dispatched to consumers.

feat: add support for rendering canvas in external windows

---

docs/js/app.js

This seems like the right thing to do otherwise any time the url bar is hidden on mobile or the download bar pops up on chrome the canvas clears.

docs: redraw on resize

---

src/signature_pad.ts
tests/signature_pad.test.ts

The recent change to the `toDataURL` function made the `type` parameter required. It was previously optional. This is a breaking change and most likely an innocent mistake.
Additionally, the type of the `encoderOptions` parameter for the second overload was corrected. The type of `type` could be `string` and its value could be `'image/svg+xml'`. So `ToSVGOptions` should be accepted by the `encoderOptions` parameter. This is not technically a breaking change but it's something I noticed while I was in the area.

fix: Fix empty `toDataURL()` in TypeScript

---

docs/js/signature_pad.umd.js
src/signature_pad.ts
tsconfig.json

Fix typescript script errors for uninitialised private properties.

---

src/signature_pad.ts
tests/fixtures/face.ts
tests/fixtures/square.ts
tests/signature_pad.test.ts

Hi there! 
I struggled a lot with implementing an `undo` and `erase` feature for my canvas.
After research, I found issue #421 which already provides a well-working version.
This PR includes the suggested changes which are provided by @JoeLeung32 (btw. thank you so much!)

fix(eraser): solves issues with eraser

---

README.md
src/signature_pad.ts
tests/signature_pad.test.ts

Allow beginStroke event to be cancelable
fixes #743

fix: make beginStroke event cancelable

---

src/signature_pad.ts
tests/signature_pad.test.ts

This PR allows to handle explicit `undefined` values in   `throttle`, `minDistance` or `canvasContextOptions` fields.
Reproduction link: https://codepen.io/username1334/pen/mdYVWVN
In the reproduction above, signature pad doesn't work because `minDistance` is `undefined`.

Use fallback values when options object contains explicit `undefined` values

---

src/bezier.ts
tests/bezier.test.ts

In some cases Bezier curve calculations could fail due to division by zero.
(for example when signature was generated by older version of the lib or another lib with similar approach to saving canvas data like this one http://keith-wood.name/signature.html)
This PR fixes the issue by checking for zero before the division.

fix: prevent division by zero in bezier
